name: Build Skyrim SKSE Plugin

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v3

    - name: Configure CMake
      run: cmake -B build -S .

    - name: Build Project (Release)
      run: cmake --build build --config Release

    - name: Upload Artifact (DLL)
      uses: actions/upload-artifact@v4
      with:
        name: MMO-Hotbar-Plugin
        path: build/Release/*.dll
